language: c
script: bash -ex .travis-ci.sh
env:
  global:
    - OPAM_DEPENDS="ocamlfind"
  matrix:
    - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
    - OCAML_VERSION=4.00.1 OPAM_VERSION=1.0.0
    - OCAML_VERSION=4.00.1 OPAM_VERSION=1.1.0
notifications:
  irc:
    channels:
      - "irc.freenode.net#frenetic"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}): %{message}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: always
