export OCAMLMAKEFILE = ./OCamlMakefile

export SOURCES = options.ml hashset.ml charset.ml nfa.ml depgraph.ml languageops.ml \
	solve.ml interface.ml parse.mly lex.mll dprle.ml
export DOC_FILES = options.ml hashset.ml charset.ml nfa.ml depgraph.ml languageops.ml \
        solve.ml interface.ml dprle.ml
export RESULT = dprle
export LIBS =
export INCDIRS = .
export PACKS = 
export OCAMLFLAGS = 
export OCAMLDOCFLAGS = -m A # Merge mli and ml file documentation


-include $(OCAMLMAKEFILE)
